spring:
  application:
    name: user-service
  datasource:
    url: 'jdbc:mysql://localhost:3306/sampleDB'
    username: root
    password: admin@1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: user
      password: gv123
server:
  port: 8386
springdoc:
  show-actuator: true
  api-docs:
    path: /authentication-service/v3/api-docs
  swagger-ui:
    enabled: true
    url: /authentication-service/v3/api-docs

# JWT Configuration
jwt:
  secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  access-token-expiration: 3600000 # 1 hour
  refresh-token-expiration: 86400000 # 1 day
  algorithm: HS256

management:
  endpoints:
    web:
      exposure:
        include: info, health, logfile, loggers, env
logging:
  file:
    name: application.log
myapp:
  message: Hello, Spring Boot!

